config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root directory
  root to: 'cocktails#index'

  resources :cocktails do
    resources :doses
  end

  delete "doses/:id", to: "doses#destroy", as: :dose

  # # show wall cocktails in the database
  # get 'cocktails', to: 'cocktails#index', as: 'cocktails'
  #
  # # take me back to the /cocktails directory after creating a new cocktail
  # post 'cocktails', to: 'cocktails#create'
  #
  # # form to fill out to create new cocktail
  # get 'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  #
  # # show details of one cocktail
  # get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  #
  # # add a new dose to the cocktail
  # get "cocktails/:id/doses/new", to: 'doses#new', as: 'new_dose'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: {scope: :ingredient}
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    cocktail_id = params[:cocktail_id]
    ingredient_id = params[:dose][:ingredient_id]
    description = params[:dose][:description]
    @dose = Dose.new(description: description, ingredient_id: ingredient_id, cocktail_id: cocktail_id)
    if @dose.save
      redirect_to cocktail_path(cocktail_id)
    else
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new
      render :new
    end

  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.4)), url('<%= cl_image_path cocktail.photo %>')">
          <div class="cocktail-name">
            <%= cocktail.name %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container-h">
    <%= link_to 'New cocktail', new_cocktail_path, {class: "add-btn"}%>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit() %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="name">
    <%= @cocktail.name %>
  </div>
  <div class="ingredients">
    <% @cocktail.doses.each do |dose| %>
      <li><%= "#{dose.description} of #{dose.ingredient.name}" %></li>
      <%= link_to "delete", dose_path(dose), method: :delete, class: "delete-btn" %>
    <% end %>
  </div>
  <%= link_to "new dose", new_cocktail_dose_path(@cocktail), {class: 'add-dose-btn'} %>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>

  <%= f.input :description %>

  <%= f.button :submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>